const collegeImages = [
    { id: 1, src: "assets/college/college 4.png", alt: "College 1" },
    { id: 2, src: "assets/college/college 5.png", alt: "College 2" },
    { id: 3, src: "assets/college/college 6.png", alt: "College 3" },
    { id: 4, src: "assets/college/college 7.png", alt: "College 4" },
    { id: 5, src: "assets/college/college 8.jpeg", alt: "College 5" },
    { id: 6, src: "assets/college/college 9.png", alt: "College 6" },
    { id: 7, src: "assets/college/college 10.png", alt: "College 7" },
    { id: 8, src: "assets/college/college 11.jpeg", alt: "College 8" },
    { id: 9, src: "assets/college/college 12.jpeg", alt: "College 9" },
    { id: 10, src: "assets/college/college 13.png", alt: "College 10" },
    { id: 11, src: "assets/college/college 14.png", alt: "College 11" },
    { id: 12, src: "assets/college/college 15.png", alt: "College 12" },
    { id: 13, src: "assets/college/college 16.jpeg", alt: "College 13" },
    { id: 14, src: "assets/college/college 17.jpeg", alt: "College 14" },
    { id: 15, src: "assets/college/college 18.png", alt: "College 15" },
    { id: 16, src: "assets/college/college 19.png", alt: "College 16" },
    { id: 17, src: "assets/college/college 20.png", alt: "College 17" },
    { id: 18, src: "assets/college/college 21.png", alt: "College 18" },
    { id: 19, src: "assets/college/college 22.png", alt: "College 19" },
    { id: 20, src: "assets/college/college 23.png", alt: "College 20" },
    { id: 21, src: "assets/college/college 24.png", alt: "College 21" },
    { id: 22, src: "assets/college/college 25.png", alt: "College 22" },
    { id: 23, src: "assets/college/college 26.png", alt: "College 23" },
    { id: 24, src: "assets/college/college 27.png", alt: "College 24" },
    { id: 25, src: "assets/college/college 28.png", alt: "College 25" },
    { id: 26, src: "assets/college/college 29.png", alt: "College 26" },
    { id: 27, src: "assets/college/college 30.png", alt: "College 27" },
    { id: 28, src: "assets/college/college 31.png", alt: "College 28" },
    { id: 29, src: "assets/college/college 32.png", alt: "College 29" },
    { id: 30, src: "assets/college/college 33.png", alt: "College 30" },
    { id: 31, src: "assets/college/college 34.png", alt: "College 31" },
    { id: 32, src: "assets/college/college 35.png", alt: "College 32" },
    { id: 33, src: "assets/college/college 36.png", alt: "College 33" },
    { id: 34, src: "assets/college/college 37.png", alt: "College 34" },
    { id: 35, src: "assets/college/college 38.png", alt: "College 35" },
    { id: 36, src: "assets/college/college 39.png", alt: "College 36" },
  ];

  export default collegeImages;